version: 2.1
jobs:
  build:
    docker:
      - image: 'emscripten/emsdk:2.0.9'
    resource_class: xlarge

    working_directory: ~/checkout

    steps:
      - checkout

      - run:
          name: Build WASM
          command: bash build-wasm.sh

      - store_artifacts:
          path: "build-wasm/wasm"
          destination: "build-wasm/wasm"
